name: POI CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '/apis/poi/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: apis/poi
      run: dotnet restore
    - name: Build
      working-directory: apis/poi
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: apis/poi/tests/UnitTests
      run: dotnet test --no-restore --verbosity normal
      
    - name: The job has failed 
      uses: alialaa/issue-action@v1
      if: failure()
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        title:  "Workflow ${{github.workflow}} | Job Status ${{job.status}}"
        body:  "Error ${{toJSON(github.event)}}"
        assignees: |
         kumarallamraju

      
