# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actionss

name: USERPROFILE CI

on:
  pull_request:
    branches:
    - master
    - release
    paths:
    - 'apis/userprofile/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm --prefix apis/userprofile install apis/userprofile 
    - run: npm --prefix apis/userprofile run test apis/userprofile 
      
    - name: 'Build Failure'
      uses: alialaa/issue-action@v1
      if: failure()
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        title:  "Workflow ${{github.workflow}} | Job Status ${{job.status}}"
        body:  "Error ${{toJSON(github.event)}}"
        assignees: |
         kumarallamraju

